# -*- coding: utf-8 -*-
############################################################
#
# Autogenerated by the KBase type compiler -
# any changes made here will be overwritten
#
############################################################

from __future__ import print_function
# the following is a hack to get the baseclient to import whether we're in a
# package or not. This makes pep8 unhappy hence the annotations.
try:
    # baseclient and this client are in a package
    from .baseclient import BaseClient as _BaseClient  # @UnusedImport
except:
    # no they aren't
    from baseclient import BaseClient as _BaseClient  # @Reimport


class hayai_annotation(object):

    def __init__(
            self, url=None, timeout=30 * 60, user_id=None,
            password=None, token=None, ignore_authrc=False,
            trust_all_ssl_certificates=False,
            auth_svc='https://kbase.us/services/authorization/Sessions/Login'):
        if url is None:
            raise ValueError('A url is required')
        self._service_ver = None
        self._client = _BaseClient(
            url, timeout=timeout, user_id=user_id, password=password,
            token=token, ignore_authrc=ignore_authrc,
            trust_all_ssl_certificates=trust_all_ssl_certificates,
            auth_svc=auth_svc)

    def hayai_annotation(self, input, context=None):
        """
        Here we define an actual function.
        :param input: instance of type "HayaiAnnotationParams" (Here we
           define the parameters that are passed from the UI The same
           parameters need to be defined in ui/narrative/methods/) ->
           structure: parameter "input_ws" of String, parameter
           "input_genome" of String, parameter "output_genome" of String,
           parameter "alignment_type" of String, parameter "organism_type" of
           String, parameter "max_hits_per_query" of Long, parameter
           "max_seq_id" of Double, parameter "max_e_value" of Double,
           parameter "query_coverage" of Double, parameter "target_coverage"
           of Double
        :returns: instance of type "HayaiAnnotationResults" (Here we define
           the output, which, for the purposes of the UI, will always be a
           report. The contents of the report are shown, in HTML, in the
           output widget.) -> structure: parameter "report_name" of String,
           parameter "report_ref" of String
        """
        return self._client.call_method(
            'hayai_annotation.hayai_annotation',
            [input], self._service_ver, context)

    def status(self, context=None):
        return self._client.call_method('hayai_annotation.status',
                                        [], self._service_ver, context)
